name: Publish package

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture'
        default: 'amd64 armhf'
      dist:
        description: 'Distribution'
        default: 'stretch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Publish package
        uses: peramic/actions/build-stretch@v1
        if: ${{ github.event.inputs.dist == 'stretch' }}
        with:
          arch: ${{ github.event.inputs.arch }}
          dist: ${{ github.event.inputs.dist }}
          script: ./mkapp
          token: ${{ secrets.ACTIONS }}
      - name: Publish package
        uses: peramic/actions/build@v1
        if: ${{ github.event.inputs.dist == 'buster' }}
        with:
          arch: ${{ github.event.inputs.arch }}
          dist: ${{ github.event.inputs.dist }}
          script: ./mkapp
          token: ${{ secrets.ACTIONS }}
